stages:
  - cache
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: javascriptonit/devsecops-bootcamp
  IMAGE_DOCKER_HUB_NAME: bkimminich/juice-shop
  IMAGE_TAG: 0.0.3-github
  SERVER_IP: 78.140.243.52
  SERVER_USER: root
  RUNNER_TAG: local-runner-docker

create_cache:
  # Устанавливает зависимости проекта и кэширует их для последующего использования
  stage: cache
  image: node:18-bullseye
  script:
    - yarn install
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
      - yarn.lock
      - .yarn
    policy: pull-push
  # when: manual
  tags:
    - $RUNNER_TAG

yarn_test:
  # Запускает тесты проекта, устанавливая зависимости из кэша
  image: node:18-bullseye
  stage: test
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
      - yarn.lock
      - .yarn
    policy: pull
  script:
    - yarn install
    - yarn global add @angular/cli
    - yarn test
  allow_failure: true
  # when: manual
  tags:
    - $RUNNER_TAG

gitleaks_check:
  # Выполняет проверку на утечки данных с помощью Gitleaks и сохраняет результаты в файл
  image: 
    name: zricethezav/gitleaks
    entrypoint: [""]
  stage: test
  script:
    - gitleaks detect --verbose --source . -f json -r gitleaks.json
  allow_failure: true
  artifacts:
    when: always
    paths: 
      - gitleaks.json
  # when: manual
  tags:
    - $RUNNER_TAG

njsscan:
  # Сканирует код на наличие уязвимостей с помощью njsscan и сохраняет результаты в SARIF формате
  image: python
  stage: test
  before_script:
    - pip3 install --upgrade njsscan
  script:
    - njsscan --exit-warning . --sarif -o njsscan.sarif
  allow_failure: true
  artifacts:
    when: always
    paths: 
      - njsscan.sarif 
  # when: manual
  tags:
    - $RUNNER_TAG

semgrep:
  # Запускает статический анализ кода с помощью Semgrep и сохраняет результаты в JSON формате
  image: semgrep/semgrep
  stage: test
  variables:
    SEMGREP_RULES: p/javascript
  script:
    - semgrep ci --json --output semgrep.json
  allow_failure: true
  artifacts:
    when: always
    paths: 
      - semgrep.json
  # when: manual
  tags:
    - $RUNNER_TAG

retire:
  # Запускает SCA анализ зависимостей с помощью  и сохраняет результаты в формате
  image: node:18-bullseye
  stage: test
  before_script:
    - npm install -g retire
  script:
    - retire --path . --outputformat json --outputpath retire.json
  allow_failure: true
  artifacts:
    when: always
    paths: 
      - retire.json
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
      - yarn.lock
      - .yarn
    policy: pull-push
  # when: manual
  tags:
    - $RUNNER_TAG

upload_reports:
  # Загружает отчеты о безопасности на сервер, используя результаты предыдущих проверок
  image: python:latest
  stage: test
  needs: ["gitleaks_check", "njsscan", "semgrep", "retire"]
  before_script:
    - pip install requests
  script:
    - python3 upload-reports.py gitleaks.json
    - python3 upload-reports.py njsscan.sarif
    - python3 upload-reports.py semgrep.json
    - python3 upload-reports.py retire.json
  # when: manual
  tags:
    - $RUNNER_TAG

build_image:
  image: docker:24
  stage: build
  services:
    - docker:24-dind
  before_script:
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  # when: manual
  tags:
    - $RUNNER_TAG

trivy:
  # Запускает сканер Docker слоёв с помощью trivy и сохраняет результаты в формате
  image: docker:24
  stage: build
  needs: ["build_image"]
  services:
    - docker:24-dind
  before_script:
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    - apk --no-cache add curl python3 py3-pip openssh-client
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.18.3
  script:
    - docker pull $IMAGE_DOCKER_HUB_NAME
    # - trivy image $IMAGE_DOCKER_HUB_NAME
    - trivy image --severity HIGH,CRITICAL --exit-code 1 $IMAGE_DOCKER_HUB_NAME
  allow_failure: true
  tags:
    - $RUNNER_TAG

deploy_image:
  stage: deploy
  image: debian:bullseye-slim
  before_script:
    - apt update -y && apt install openssh-client -y
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $IMAGE_NAME:$IMAGE_TAG"
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker stop juice-shop || true && docker rm -f juice-shop || true"
    # - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 3000:3000 --name juice-shop $IMAGE_NAME:$IMAGE_TAG"
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 3002:3000 --name juice-shop $IMAGE_DOCKER_HUB_NAME"
  when: manual
  tags:
    - $RUNNER_TAG